import { createSlice } from '@reduxjs/toolkit';
import type { Element, Widget} from '../../types/modalities';

type InitialState = {
  visualComplexity: number;
  audioComplexity: number;
  widgets: Widget[];
  grid: Widget[][];

  /* ADD MORE AS NEEDED... */
};

const initialState: InitialState = {
  visualComplexity: 0,
  audioComplexity: 0,
  widgets: [],
  grid: new Array(4).fill(null).map(() => new Array(4).fill(null)), //grid that holds ids of widgets in locations
};

export const cmSlice = createSlice({
  name: 'cm',
  initialState,
  // reducers are used to update the state
  reducers: {
    addWidgetToGrid: (state, action) => { //add a widget to the grid at the location specified in inputted widget
      state.grid[action.payload.location[0]][action.payload.location[1]] = action.payload.id;
      console.log(state.grid);
    },
    deleteWidgetFromGrid: (state, action) => { //remove a widget from the grid from the location specified in inputted widget
      console.log(action.payload)
      state.grid[action.payload.location[0]][action.payload.location[1]] = null as any;
    },
    addWidget: (state, action) => {
      state.widgets.push(action.payload);
    },
    removeWidget: (state, action) => {
      let tempWidgets = state.widgets;
      tempWidgets.forEach(function(widget,widgetIndex){ //go through each widget
          if(widget.id == action.payload){
              tempWidgets = tempWidgets.splice(widgetIndex, widgetIndex);
          }
      });

      state.widgets = tempWidgets;
    },
    
    updateWidgetDelete: (state, action) => {//remove elements from widget
      const tempWidgets = state.widgets;
      tempWidgets.forEach(function(widget,widgetIndex){ //go through each widget
        widget.elements.forEach(function(element, elementIndex) { //go through each element
          if(element.id == action.payload){
              widget.elements = widget.elements.splice(elementIndex, elementIndex);
          }
          
        });
      });

      state.widgets = tempWidgets;
      
    },
    updateVisualComplexity: (state, action) => {},
    updateAudioComplexity: (state, action) => {},
  },
  // selectors are used to access parts of the state within components
  selectors: {
    getWidgets: (state) => state.widgets,
    // find a single widget by id
    getWidgetById: (state, id: string) =>
      state.widgets.find((widget) => widget.id === id),
    getVisualComplexity: (state) => state.visualComplexity,
    getAudioComplexity: (state) => state.audioComplexity,
  },
});

// action creators (automatically generated by createSlice for each reducer)
export const {
  addWidgetToGrid,
  deleteWidgetFromGrid,
  addWidget,
  removeWidget,
  updateWidgetDelete,
  updateVisualComplexity,
  updateAudioComplexity,
} = cmSlice.actions;

export const {
  getWidgets,
  getWidgetById,
  getVisualComplexity,
  getAudioComplexity,
} = cmSlice.selectors;
