import { createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit';
import type { Widget } from 'src/types/widget';
import type { Message } from 'src/types/schema-types';
import type { Element } from 'src/types/element';
import type { LinkedSectionWidget, Section } from 'src/types/support-types';
import { initialSections } from 'src/redux/utils/initialSections';
import { ownship, drones, initialShips } from 'src/utils/initialShips';

type InitialState = {
  visualComplexity: number;
  audioComplexity: number;
  widgets: Widget[];
  messages: Message[];
  sections: Section[];
};

const initialState: InitialState = {
  visualComplexity: 0,
  audioComplexity: 0,
  widgets: initialShips,
  messages: [],
  sections: initialSections,
};

export const minimapSlice = createSlice({
  name: 'minimap',
  initialState,
  // reducers are used to update the state
  reducers: {
    addMapSection: (state, action) => {
      state.sections.push(action.payload); //add it to our sections as well
    },

    addWidget: (state, action: PayloadAction<Widget>) => {
      state.widgets.push(action.payload); //add to the widgets
    },

    updateWidget: (state, action: PayloadAction<Widget>) => {
      state.widgets = state.widgets.map((widget) =>
        widget.id === action.payload.id ? action.payload : widget,
      );
    },

    removeWidget: (state, action: PayloadAction<string>) => {
      state.widgets = state.widgets.filter(
        (widget) => widget.id !== action.payload,
      );
    },

    addElementToWidget: {
      prepare(widgetId: string, element: Element) {
        return { payload: { widgetId, element } };
      },

      reducer(
        state,
        action: PayloadAction<{ widgetId: string; element: Element }>,
      ) {
        state.widgets = state.widgets.map((widget) => {
          if (widget.id === action.payload.widgetId) {
            widget.elements.push(action.payload.element);
            return widget;
          }
          return widget;
        });
      },
    },

    addWidgetToSection: (state, action: PayloadAction<LinkedSectionWidget>) => {
      state.sections.forEach(function (section, sectionIndex) {
        if (section.id === action.payload.sectionID) {
          section.widgetIDs.push(action.payload.widgetID);
        }
      });
    },

    // delete an element from a widget by id
    updateWidgetDelete: (state, action: PayloadAction<string>) => {
      state.widgets = state.widgets.map((widget) => {
        return {
          ...widget,
          elements: widget.elements.filter(
            (element) => element.id !== action.payload,
          ),
        };
      });
    },

    toggleElementInteraction: (state, action: PayloadAction<string>) => {
      state.widgets = state.widgets.map((widget) => {
        if (widget.id === action.payload) {
          return {
            ...widget,
            elements: widget.elements.map((element) => {
              return {
                ...element,
                interacted: !element.interacted,
              };
            }),
          };
        }
        return widget;
      });
    },

    updateVisualComplexity: (state, action: PayloadAction<number>) => {
      state.visualComplexity = action.payload;
    },
    updateAudioComplexity: (state, action: PayloadAction<number>) => {
      state.audioComplexity = action.payload;
    },

    addMessage: (state, action: PayloadAction<Message>) => {
      state.messages.push(action.payload);
    },
  },
  // selectors are used to access parts of the state within components
  selectors: {
    getSections: (state) => state.sections,
    getWidgets: (state) => state.widgets,
    // find a single widget by id
    getWidgetById: (state, id: string) =>
      state.widgets.find((widget) => widget.id === id),
    getVisualComplexity: (state) => state.visualComplexity,
    getAudioComplexity: (state) => state.audioComplexity,
    getMessages: (state) => state.messages,
    getOwnship: (state) =>
      state.widgets.find((widget) => widget.id === ownship.id),
    getDrones: (state) =>
      state.widgets.filter((widget) =>
        drones.map((drone) => drone.id).includes(widget.id),
      ),
  },
});

// action creators (automatically generated by createSlice for each reducer)
export const {
  addMapSection,
  addMessage,
  addWidget,
  updateWidget,
  removeWidget,
  addElementToWidget,
  addWidgetToSection,
  updateWidgetDelete,
  updateVisualComplexity,
  updateAudioComplexity,
  toggleElementInteraction,
} = minimapSlice.actions;

export const {
  getSections,
  getWidgets,
  getWidgetById,
  getMessages,
  getOwnship,
  getDrones,
  getVisualComplexity,
  getAudioComplexity,
} = minimapSlice.selectors;
